### ISSUE TITLE
set pi hostname - plugin used for pi-hole

### ISSUE THREAD

**Issue by gitty8** [graylog-labs/graylog-plugin-threatintel#43]
I found your plugin from this project:
https://jalogisch.de/2017/der-eigene-dns-resolver-zuhause/

and used this pipeline rules:
https://gist.github.com/jalogisch/922b7a3438c5c6f5b9d02557d33ab2eb

Maybe someone knows what is being used at stage -9 for set pi host name? I tried everything from documentation at graylog, but not works.

thanks

**Comment by lennartkoopmann** [comment]
set_field("source", "new-hostname")

**Comment by gitty8** [comment]
like this?

```
rule "set pi hostname"
when
    has_field("application_name") AND contains(to_string($message.application_name), "pihole")
then
set_field("source", "pihole");
end
```

**Comment by lennartkoopmann** [comment]
That should work. Or you connect the pipeline to a stream that only contains messages from your pi and skip the `contains()` part of your rule. This would definitely improve performance.

Locking this issue because it's not related to the threat intel plugin. You can read more about pipelines [here](http://docs.graylog.org/en/2.2/pages/pipelines.html) and ask questions in our [community forum](https://community.graylog.org/)
